"""initial schema
Revision ID: d04be5f10e5b
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = 'd04be5f10e5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    _append_only_rules_up()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chaos_injections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('fault_id', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('armed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effect_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("state in ('ARMED','FIRED','EXPIRED','DISARMED')", name='ck_chaos_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chaos_fault', 'chaos_injections', ['fault_id', 'state'], unique=False)
    op.create_table('dead_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('arm', sa.String(length=32), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.Text(), nullable=False),
    sa.Column('taxonomy_version', sa.Text(), nullable=False),
    sa.Column('constraint_version', sa.Text(), nullable=False),
    sa.Column('llm_mode', sa.String(length=16), nullable=False),
    sa.Column('faults_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("arm in ('ARM_CONTROL','ARM_DUNNFLOW')", name='ck_run_arm'),
    sa.CheckConstraint('n > 0 and n <= 2000', name='ck_run_n'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_runs_status_started', 'runs', ['status', 'started_at'], unique=False)
    op.create_index('uq_runs_active', 'runs', ['seed', 'arm'], unique=True, postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.create_table('audit_log',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('case_ref', sa.String(length=32), nullable=True),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('node', sa.String(length=32), nullable=True),
    sa.Column('state_from', sa.String(length=32), nullable=True),
    sa.Column('state_to', sa.String(length=32), nullable=True),
    sa.Column('rule_id', sa.String(length=48), nullable=True),
    sa.Column('policy_version', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('classifier_tier', sa.String(length=4), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index('ix_audit_case', 'audit_log', ['case_id', 'seq'], unique=False)
    op.create_index('ix_audit_run', 'audit_log', ['run_id', 'seq'], unique=False)
    op.create_index('ix_audit_type', 'audit_log', ['entry_type', 'occurred_at'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('case_ref', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=64), nullable=False),
    sa.Column('obligation_ref', sa.String(length=64), nullable=False),
    sa.Column('failure_class', sa.String(length=48), nullable=False),
    sa.Column('failure_family', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=48), nullable=True),
    sa.Column('classifier_tier', sa.String(length=4), nullable=True),
    sa.Column('classifier_conf', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('money_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("classifier_tier in ('T1','T2','T3','T4')", name='ck_case_tier'),
    sa.CheckConstraint('amount_minor > 0', name='ck_case_amount_positive'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'case_ref', name='uq_case_run_ref'),
    sa.UniqueConstraint('run_id', 'obligation_ref', name='uq_case_run_obligation')
    )
    op.create_index('ix_cases_cursor', 'cases', ['run_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_cases_run_class', 'cases', ['run_id', 'failure_class'], unique=False)
    op.create_index('ix_cases_run_status', 'cases', ['run_id', 'status'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('gateway_ref', sa.String(length=64), nullable=True),
    sa.Column('error_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome in ('IN_FLIGHT','SUCCEEDED','FAILED','AMBIGUOUS')", name='ck_attempt_outcome'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'attempt_index', name='uq_attempt_case_index'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_attempts_case', 'attempts', ['case_id', 'attempt_index'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=32), nullable=False),
    sa.Column('state_from', sa.String(length=32), nullable=True),
    sa.Column('state_to', sa.String(length=32), nullable=True),
    sa.Column('rule_id', sa.String(length=48), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'seq', name='uq_event_case_seq')
    )
    op.create_index('ix_events_case_seq', 'case_events', ['case_id', 'seq'], unique=False)
    op.create_table('constraint_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('constraint_id', sa.String(length=48), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reschedule_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposed_action', sa.String(length=32), nullable=False),
    sa.Column('rule_id', sa.String(length=48), nullable=True),
    sa.Column('failure_class', sa.String(length=48), nullable=True),
    sa.Column('unverified', sa.Boolean(), nullable=False),
    sa.Column('constraint_version', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision in ('ALLOW','DENY','SKIPPED')", name='ck_ce_decision'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ce_case_pos', 'constraint_evaluations', ['case_id', 'position'], unique=False)
    op.create_index('ix_ce_run_decision', 'constraint_evaluations', ['run_id', 'decision'], unique=False)
    op.create_index('ix_ce_run_denies', 'constraint_evaluations', ['run_id', 'constraint_id'], unique=False, postgresql_where=sa.text("decision = 'DENY'"))
    op.create_table('exception_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('confirmed_case_ref', sa.String(length=32), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision in ('APPROVED','REJECTED')", name='ck_exdec'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('scheduled_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('directive', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.CheckConstraint("status in ('PENDING','CLAIMED','DONE','CANCELLED')", name='ck_sched_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sched_due', 'scheduled_actions', ['run_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


    _post_upgrade_rules()

def _append_only_rules_up() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sched_due', table_name='scheduled_actions', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('scheduled_actions')
    op.drop_table('exception_decisions')
    op.drop_index('ix_ce_run_denies', table_name='constraint_evaluations', postgresql_where=sa.text("decision = 'DENY'"))
    op.drop_index('ix_ce_run_decision', table_name='constraint_evaluations')
    op.drop_index('ix_ce_case_pos', table_name='constraint_evaluations')
    op.drop_table('constraint_evaluations')
    op.drop_index('ix_events_case_seq', table_name='case_events')
    op.drop_table('case_events')
    op.drop_index('ix_attempts_case', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('ix_cases_run_status', table_name='cases')
    op.drop_index('ix_cases_run_class', table_name='cases')
    op.drop_index('ix_cases_cursor', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_audit_type', table_name='audit_log')
    op.drop_index('ix_audit_run', table_name='audit_log')
    op.drop_index('ix_audit_case', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('uq_runs_active', table_name='runs', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.drop_index('ix_runs_status_started', table_name='runs')
    op.drop_table('runs')
    op.drop_table('dead_letters')
    op.drop_index('ix_chaos_fault', table_name='chaos_injections')
    op.drop_table('chaos_injections')
    # ### end Alembic commands ###


def _post_upgrade_rules() -> None:
    """Append-only enforced at the database, not by convention."""
    op.execute("CREATE RULE audit_log_no_update AS ON UPDATE TO audit_log DO INSTEAD NOTHING")
    op.execute("CREATE RULE audit_log_no_delete AS ON DELETE TO audit_log DO INSTEAD NOTHING")
